server:
  port: 9001
spring:
  application:
    name: prome-config
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/dongxiaochen5535/prome-config.git # 配置git仓库的地址
          search-paths: /** 
          username: dongxiaochen5535                         # git仓库的账号
          password: dxc1314@zpn                           	# git仓库的密码
          force-pull: true
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-cloud-config
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:xiMNZtbZrDzuc7G7@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
