external-risk:
  baiduRockAddressUrl : https://jrws.baidu.com/risk/api/info/check/address?
  baiduRockSearchUrl : https://jrws.baidu.com/risk/api/info/search?
  bairongStrategyId : STR0002136
  geoTokenUrl : /civp/getview/api/o/login?
  geoQueryUrl : /civp/getview/api/u/queryUnify
  geoFileUrl : /ofiles/openapi/jiao/
  fiveDFileUrl : /ofiles/openapi/wuwei/
  shenyueFileUrl : /ofiles/openapi/shenyue/
  tencentAntiFraud : AntiFraud
  tencentGz : gz
  
tongdun:
  partner:
      code: xianhuahua_in
      key: 65e9d107884e4800927389e8a6e13e6d
  app:
    name: test_and
  biz:
    code:
      register: dqshand
      loan: zcshand
  gjxd:
    url: https://apitest.tongdun.net/aurora/apply/v1
