#开发环境业务配置

logging:
  level:
    com.xhh.baidu: debug
  config: classpath:logback/logback-dev.xml

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

